### ISSUE TITLE
Works not in KDE 6

### ISSUE THREAD

**Issue by wadaki** [samirgaire10/com.samirgaire10.Deepl#1]
If you add the widget into KDE 6, KDE will stop working anymore. This is very critical, it's possible to update the widget for Plasma 6?

**Comment by samirgaire10** [comment]
There is another one for kde 6    link-->   https://github.com/samirgaire10/com.samirgaire10.Deepl-plasma6

**Comment by wadaki** [comment]
I used this and it doesn't work with Plasma 6.
これを使いましたが、Plasma 6では動作しません。その他のWidget（ChatGPT）は同じです。

**Comment by samirgaire10** [comment]
もっと説明お願いいたします。日本語でもいいから。実在
plasma 5のこれで             https://github.com/samirgaire10/com.samirgaire10.Deepl
plasma 6 のこれで　　　 https://github.com/samirgaire10/com.samirgaire10.Deepl-plasma6

で俺のLinux のPC壊れっているのでテストはできないです。すみません！！！

**Comment by wadaki** [comment]
I can download the widget as well. After that I will add the widget into the panel. Than the hole screen will be black and blinking 2 times before come back. I can see the opened windows, but all the panel are gone and the desktop background is black. KDE is broken. (For other users, I will use English language.)

**Comment by samirgaire10** [comment]
I am sorry ,  My linux pc was broken so please install   
---->  https://github.com/samirgaire10/com.samirgaire10.Google-plasma6   
this is a google widget same just for google.com  .... In this widget there is a search bar above use deepl.com url   for now ..........
sorry ,, after i install linux i will test the issue  and try to fix it ... sooooooorrrrryyy for your inconvenience
